[theme]
primaryColor="#800080"  # A classic shade of purple
backgroundColor="#F4E1F1"  # A soft lavender background that's calming and inviting
secondaryBackgroundColor="#E6CEE8"  # A gentle purple for secondary elements
textColor="#483D8B"  # Dark slate blue for text, complementing the purple tones
font="sans serif"
