[theme]
primaryColor="#FFA500"  # A vibrant shade of orange
backgroundColor="#FFF5E1"  # A light orange background that's easy on the eyes
secondaryBackgroundColor="#FFE4B5"  # A softer orange for secondary elements
textColor="#005A9C"  # A deep blue for contrast with orange
font="sans serif"
